# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_auto_20170815_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
